#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8
bspc config normal_border_color		"#323232"
bspc config focused_border_color  	"#F19618"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Nitrogen state=floating
bspc rule -a pqiv state=floating

nitrogen --restore &
picom -b &
discord --start-minimized &

