#!/usr/bin/env sh

hex2rgb() {
	read -r hex
	hex="$(echo $hex | cut -c2-)"
	# echo $hex
	local r="$(echo $hex | cut -c-2)"
	local g="$(echo $hex | cut -c3-4)"
	local b="$(echo $hex | cut -c5-6)"
	# echo $r $g $b
	printf "%d;%d;%d" "0x${r}" "0x${g}" "0x${b}"
}
# Foreground: \e[38;2
# Background: \e[48;2
ACCENT_COLOR="$(xrdb -get accent | hex2rgb)"
NORMAL_COLOR="$(xrdb -get foreground | hex2rgb)"

fgcolor() {
	read -r rgb
	printf "\e[38;2;%sm" "${rgb}"
}

print() {
	[ -z "${2}" ] || printf "${bold}%s%-10s${reset} %s%s\n" "${accent}" "${1:-NULL}" "${normal}" "${2}"
}

reset="\e[0m"
bold="\e[1m"

accent="$(echo "${ACCENT_COLOR}" | fgcolor)"
normal="$(echo "${NORMAL_COLOR}" | fgcolor)"

art="${accent}      /\\
     /  \\
    /\\   \\
${normal}   /      \\
  /   ,,   \\
 /   |  |  -\\
/_-''    ''-_\\"

[ "${1}" = "art" ] && printf "${bold}%s${reset}\n" "${art}" && exit 0

neofetch=$(neofetch --stdout)
uptime="$(echo "${neofetch}" | grep Uptime | cut -f2 | tr '[:upper:]' '[:lower:]')"
terminal="$(echo "${neofetch}" | grep Terminal | cut -f2 | tr '[:upper:]' '[:lower:]')"
shell="$(echo "${neofetch}" | grep Shell | cut -f2 | tr '[:upper:]' '[:lower:]')"
wm="$(echo "${neofetch}" | grep WM | cut -f2 | tr '[:upper:]' '[:lower:]')"
theme="$(echo "${neofetch}" | grep Theme | cut -f2 | tr '[:upper:]' '[:lower:]')"
icons="$(echo "${neofetch}" | grep Icons | cut -f2 | tr '[:upper:]' '[:lower:]')"

print "os" "  arch linux"
print "uptime" " ${uptime}"
print "terminal" "  kitty"
print "shell" " ${shell}"
print "wm" "缾${wm}"
print "theme" " ${theme}"
print "icons" " ${icons}"
