#!/usr/bin/env sh

################
# LOAD PROFILE #
################
. "${HOME}/.profile"

#########################
# BERRYWM CONFIGURATION #
#########################

# Decoration
berryc decorate_new false

# Set decoration geometry
berryc border_width          4
berryc inner_border_width    0
berryc title_height          0
# berryc top_gap               48
berryc edge_gap              48 8 8 8

# Set decoration colors
berryc focus_color           131721
berryc unfocus_color         0E1419
berryc inner_focus_color     131721
berryc inner_unfocus_color   0E1419
berryc text_focus_color      E5E1CF
berryc text_unfocus_color    BFBDB6

# Workspace options
# berryc name_desktop 0 一
# berryc name_desktop 1 ニ
# berryc name_desktop 2 三
# berryc name_desktop 3 四
# berryc name_desktop 4 五
# berryc name_desktop 5 六
# berryc name_desktop 6 七
# berryc name_desktop 7 八
# berryc name_desktop 8 九
# berryc name_desktop 9 十
berryc name_desktop 0 " "
berryc name_desktop 1 " "
berryc name_desktop 2 " "
berryc name_desktop 3 " "
berryc name_desktop 4 " "
berryc name_desktop 5 " "
berryc name_desktop 6 " "
berryc name_desktop 7 "ﳨ "
berryc name_desktop 8 " "
berryc name_desktop 9 " "

# Other options
berryc set_font              "xft:Rubik:size=10:style=Bold"
berryc draw_text             false
berryc smart_place           true
berryc edge_lock             true
berryc focus_follows_pointer false
berryc move_mask ctrl

# wallpaper
feh "--bg-${WALLPAPER_MODE}" "${WALLPAPER_DIRECTORY}/${WALLPAPER}" &

# panel
pgrep -x polybar        || "${HOME}/.config/polybar/launch.sh"     &

# if reload, do not run app
[ "${1}" = "reload" ] && exit 0

#########################
# APPLICATION AUTOSTART #
#########################

# fix berry focus window but not switching workspace
"${HOME}"/.scripts/berry_focus_fix      &

# fix cursor
xsetroot -cursor_name left_ptr          &

# hotkey daemon
sxhkd -c ~/.config/berry/sxhkdrc        &

# compositor
picom -b                                &

# notification daemon
dunst                                   &

# input daemon
ibus-daemon -dxrR                       &

# clipboard daemon
copq                                    &

# chat client
ping -c 1 discord.com && discord        &
